name: 'release'
on:
  release:
    types: [created]
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Antikythera
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/antikythera/build-rpm:latest
            ghcr.io/antikythera/build-rpm:v1
            ghcr.io/antikythera/build-rpm:${{ steps.get_release.outputs.tag_name }}
