name: 'test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            localhost:5000/antikythera/build-rpm:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}

      - uses: docker://localhost:5000/antikythera/build-rpm:latest
        with:
          spec_file: 'rpm_assets/hello_world.spec'
          sources: |
            rpm_assets/hello.tar.gz
          variables: |
            _version=1.0.0
            _foo=bar
