name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: |
          npm install
      - run: |
          npm run all
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Antikythera
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            antikythera/build-rpm:latest

  test:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v2
      - uses: Antikythera/build-rpm@latest
        with:
          spec_file: 'repo/frame-cpanel-rpm.spec'
          sources: |
            rpm_assets/hello.tar.gz
          variables: |
            _version=1.0.0
            _foo=bar
